name: deploy-toy-website-environments
concurrency: toy-company

on: 
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  
  # Lint the Bicep file.
  lint: 
    uses: rfrazier/ghdeployments/.github/workflows/lint.yml@main
  
  # Deploy to the test environment.
  deploy-test:
    uses: rfrazier/ghdeployments/.github/workflows/deploy.yml@main
    needs: lint
    with:
      environmentType: Test
      resourceGroupName: GHDeployments_Test
      reviewApiUrl: https://sandbox.contoso.com/reviews
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS_TEST }}
      reviewApiKey: ${{ secrets.REVIEW_API_KEY_TEST }}
  
  # Deploy to the production environment.
  deploy-production:
    uses: rfrazier/ghdeployments/.github/workflows/deploy.yml@main
    needs: deploy-test
    with:
      environmentType: Production
      resourceGroupName: GHDeployments_Prod
      reviewApiUrl: https://api.contoso.com/reviews
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS_PROD }}
      reviewApiKey: ${{ secrets.REVIEW_API_KEY_PRODUCTION }}
